-- DeutschLernen Supabase schema
-- Required by server.js when SUPABASE_URL and SUPABASE_SERVICE_KEY are set.
-- The application uses the service_role key server-side only; do not expose it to the browser.

create table if not exists public.users (
  username text primary key,
  password_hash text not null,
  data jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create table if not exists public.sessions (
  token text primary key,
  username text not null references public.users(username) on delete cascade,
  last_used timestamptz not null default now()
);

create index if not exists sessions_username_idx on public.sessions(username);
create index if not exists sessions_last_used_idx on public.sessions(last_used);

comment on table public.users is 'DeutschLernen app users and synced learning data.';
comment on column public.users.username is 'Application username; primary user identifier.';
comment on column public.users.password_hash is 'Password hash generated by server.js.';
comment on column public.users.data is 'Full synced app data blob: saved phrases, chat logs, stats, and settings.';
comment on table public.sessions is 'Bearer token sessions used by x-token authentication.';
comment on column public.sessions.token is 'Random 32-byte hex session token.';
comment on column public.sessions.last_used is 'Refreshed on authenticated requests and used for 30-day cleanup.';
